#!/bin/bash

#Настройка прав пользователя
#----статус администратора
#----добавление в группы

#Добавление сторонних репозиториев:
#Yandex-browser
#SublimeText
#Skype
#Zoom

#Обновление системы
sudo apt update
sudo apt -y upgrade

#Установка программ
sudo apt -y install mc neofetch git python3-pip planner openvpn network-manager-openvpn-gnome
pip3 install virtualenv

#Настройка программ
#----настройка git

#Завершение установок и настройки системы
sudo apt -y autoremove

